; ALLOWS ONE TO START THE APPLICATION WITH RUN
; SYS 2064
*=$0801 
         BYTE $0C, $08, $0A, $00, $9E, $20, $32, $30, $36, $34, $00, $00, $00, $00, $00

CIA1IRQ         = $DC0D
RASTERREG       = $D011
IRQRASTER       = $D012
IRQADDRMSB      = $0314
IRQADDRLSB      = $0315
IRQCTRL         = $D01A
IRQFLAG         = $D019
IRQFINISH       = $EA31
PORTB           = $DC01
VFMODE          = $D418

INIT    LDA #%01111111 ; SWITCH OFF CIA-1 INTERRUPTS
        STA CIA1IRQ

        AND RASTERREG ; CLEAR VIC RASTER REGISTER
        STA RASTERREG

        LDA #250 ; SETUP PLAY INTERRUPT AT RASTER LINE 250 FOR TIMING
        STA IRQRASTER
        LDA #<PLAYIRQ
        STA IRQADDRMSB
        LDA #>PLAYIRQ
        STA IRQADDRLSB

        LDA #%00000001 ; RE-ENABLE RASTER INTERRUPTS ONLY AFTER SETUP
        STA IRQCTRL

CLEAN   LDA #0 ; CLEAR SID VOLUME AND FILTERS,
        STA VFMODE
        RTS ; AND THEN QUIT

PLAYIRQ ; TODO
        ASL IRQFLAG ; RESET IRQ FLAG
        JMP IRQFINISH ; LET MACHINE HANDLE OTHER IRQS

